"""
Markdown report generation for backtest results.

Generates human-readable reports with configuration details,
performance summary, risk metrics, and assumptions.
"""

import uuid
from datetime import datetime, timezone

from pmirror.domain.models import BacktestMetrics


def generate_markdown_report(
    metrics: BacktestMetrics,
    config: dict,
    run_id: str | None = None,
) -> str:
    """
    Generate a markdown report from backtest metrics.

    Args:
        metrics: BacktestMetrics from completed backtest
        config: Configuration dict with wallet, policy, dates, etc.
        run_id: Optional run identifier (generated if not provided)

    Returns:
        Markdown formatted report string
    """
    if run_id is None:
        run_id = str(uuid.uuid4())[:8]

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")

    # Extract configuration values with defaults
    wallet = config.get("wallet", "N/A")
    policy = config.get("policy", "N/A")
    start_date = config.get("start", "N/A")
    end_date = config.get("end", "N/A")
    initial_cash = config.get("initial_cash", 10000.0)

    # Build report
    report = f"""# Backtest Report: {run_id}

**Generated:** {now}

## Configuration

| Parameter | Value |
|-----------|-------|
| Wallet | `{wallet}` |
| Policy | {policy} |
| Start Date | {start_date} |
| End Date | {end_date} |
| Initial Cash | ${initial_cash:,.2f} |

## Performance Summary

| Metric | Value |
|--------|-------|
| Initial Cash | ${initial_cash:,.2f} |
| Final Cash | ${metrics.final_equity:,.2f} |
| Peak Equity | ${metrics.peak_equity:,.2f} |
| Total Return | {metrics.total_return * 100:.2f}% |
"""

    if metrics.target_return != 0:
        report += f"| Target Return | {metrics.target_return * 100:.2f}% |\n"

    report += f"""
## Risk Metrics

| Metric | Value |
|--------|-------|
| Sharpe Ratio | {metrics.sharpe_ratio:.2f} |
| Sortino Ratio | {metrics.sortino_ratio:.2f} |
| Max Drawdown | {metrics.max_drawdown * 100:.2f}% |
| Max DD Duration | {_format_duration(metrics.max_drawdown_duration)} |

## Trade Statistics

| Metric | Value |
|--------|-------|
| Total Trades | {metrics.total_trades} |
| Win Rate | {metrics.win_rate * 100:.1f}% |
| Avg Trade Return | {metrics.avg_trade_return * 100:.2f}% |
| Skipped Trades | {metrics.skipped_trades} |
| Skip Rate | {metrics.skipped_rate * 100:.1f}% |

## Exposure Analysis

| Metric | Value |
|--------|-------|
| Max Exposure | ${metrics.max_exposure:,.2f} |
| Avg Exposure | ${metrics.avg_exposure:,.2f} |
"""

    if metrics.exposure_by_market:
        report += "### Exposure by Market\n\n"
        report += "| Market | Exposure |\n"
        report += "|--------|----------|\n"
        for market_id, exposure in metrics.exposure_by_market.items():
            report += f"| `{market_id[:16]}...` | ${exposure:,.2f} |\n"

    report += f"""
## Costs

| Metric | Value |
|--------|-------|
| Total Fees | ${metrics.total_fees:,.2f} |

## Assumptions & Limitations

- **Execution price:** Uses target trade price with slippage applied
- **Order book:** Real-time orderbook depth not available
- **Partial fills:** Assumed full fills on all orders
- **Market impact:** Simplified slippage model (fixed bps)
- **Latency:** Policy-specified execution delay
- **Liquidity:** No liquidity constraints modeled

## Next Steps

Review the trade log and adjust parameters as needed. Consider:
- Optimizing position sizing
- Adjusting latency settings
- Filtering low-liquidity markets
- Adding risk management rules

---
*Generated by pmirror - Polymarket Copy-Trade Backtest System*
"""

    return report


def _format_duration(duration: any) -> str:
    """Format a timedelta duration for display."""
    if duration is None:
        return "N/A"

    if isinstance(duration, (int, float)):
        # Assume it's in seconds
        duration = __import__("datetime").timedelta(seconds=duration)

    total_seconds = int(duration.total_seconds())

    if total_seconds < 60:
        return f"{total_seconds}s"
    elif total_seconds < 3600:
        minutes = total_seconds // 60
        return f"{minutes}m"
    elif total_seconds < 86400:
        hours = total_seconds // 3600
        return f"{hours}h"
    else:
        days = total_seconds // 86400
        return f"{days}d"


def save_report(
    report: str,
    run_id: str,
    reports_dir: str = "reports",
) -> str:
    """
    Save report to file system.

    Args:
        report: Markdown report content
        run_id: Run identifier for subdirectory
        reports_dir: Base directory for reports

    Returns:
        Full path to saved report file
    """
    from pathlib import Path

    reports_path = Path(reports_dir)
    run_path = reports_path / run_id
    run_path.mkdir(parents=True, exist_ok=True)

    report_file = run_path / "report.md"
    report_file.write_text(report)

    return str(report_file)
