"""Core data models for the Polymarket trading bot.

All models use Pydantic v2 BaseModel for validation at construction time.
External data (API responses, JSONL snapshots) should always be constructed
via these models so validation runs at the boundary.
"""
import uuid
from datetime import datetime
from typing import Literal
from pydantic import BaseModel, Field, model_validator
from typing_extensions import Self


class MarketState(BaseModel):
    """Snapshot of a Polymarket prediction market.

    Validates that YES and NO prices sum to approximately $1.00,
    with a 1-cent tolerance for API rounding differences.
    """
    market_id: str
    question: str
    yes_price: float = Field(ge=0.0, le=1.0)
    no_price: float = Field(ge=0.0, le=1.0)
    volume_24h: float = Field(ge=0.0)
    timestamp: datetime

    @model_validator(mode="after")
    def prices_sum_to_one(self) -> Self:
        """YES + NO must sum to ~1.00 (±0.01 tolerance for API rounding)."""
        total = round(self.yes_price + self.no_price, 4)
        if abs(total - 1.0) > 0.01:
            raise ValueError(
                f"YES ({self.yes_price}) + NO ({self.no_price}) = {total}, expected ~1.00"
            )
        return self


class Signal(BaseModel):
    """Trading signal generated by a strategy.

    direction: one of BUY_YES, BUY_NO, SELL_YES, SELL_NO
    confidence: [0.0, 1.0] — strategy's confidence in the signal
    price: target entry price for the signal
    reason: human-readable explanation of why signal was generated
    """
    market_id: str
    direction: str
    confidence: float = Field(ge=0.0, le=1.0)
    price: float = Field(ge=0.0, le=1.0)
    reason: str


class SimulatedOrder(BaseModel):
    """Record of a simulated (paper) order fill.

    Created when the bot decides to act on a signal in mock/replay mode.
    In Phase 1, all orders are simulated — no real API calls are made.

    order_id is auto-generated as a UUID4 string so that cancel_order()
    can reference the order unambiguously.
    status tracks the order lifecycle: OPEN -> FILLED or OPEN -> CANCELLED.
    """
    order_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    market_id: str
    side: str        # "YES" or "NO"
    direction: str   # "BUY" or "SELL"
    fill_price: float = Field(ge=0.0, le=1.0)
    quantity: float = Field(ge=0.0)
    status: Literal["OPEN", "FILLED", "CANCELLED"] = "OPEN"
    timestamp: datetime


class OpenPosition(BaseModel):
    """An open (unrealized) position in a prediction market.

    Stored by RiskManager. Used for stop-loss detection and PnL calculation.

    side:             "YES" or "NO" — which token is held
    direction:        "BUY" (always BUY for an open long position)
    entry_price:      price paid per token (fill_price from SimulatedOrder)
    quantity:         number of tokens held (max_position_size / fill_price)
    stop_loss_price:  price at which stop fires (entry_price * (1 - stop_loss_pct))
    opened_at:        timestamp when the position was opened
    """
    market_id: str
    side: str              # "YES" or "NO"
    direction: str         # "BUY"
    entry_price: float = Field(ge=0.0, le=1.0)
    quantity: float = Field(gt=0.0)
    stop_loss_price: float = Field(ge=0.0, le=1.0)
    opened_at: datetime
